# Generated by Django 5.1.2 on 2024-10-19 13:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="profile_pic",
            field=models.ImageField(null=True, upload_to="Media/Profile_Pic"),
        ),
    ]
