# Generated by Django 5.1.1 on 2024-10-20 03:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_alter_customuser_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='Age',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='Contact_No',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='Gender',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='profile_pic',
        ),
        migrations.RemoveField(
            model_name='viewersprofilemodel',
            name='Bio',
        ),
        migrations.RemoveField(
            model_name='viewersprofilemodel',
            name='interests',
        ),
        migrations.RemoveField(
            model_name='viewersprofilemodel',
            name='location',
        ),
        migrations.RemoveField(
            model_name='viewersprofilemodel',
            name='preferred_content_type',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('viewers', 'Viewers'), ('creator', 'Creator')], max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='creatorProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bloggersProfile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='BloggerProfileModel',
        ),
    ]
