# Generated by Django 5.1.1 on 2024-10-20 04:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_remove_customuser_age_remove_customuser_contact_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creatorprofilemodel',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='creatorsProfile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='RecipeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner')], max_length=100, null=True)),
                ('Difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], max_length=100, null=True)),
                ('Tag', models.CharField(choices=[('Vegetarian', 'Vegetarian'), ('Non_Vegetarian', 'Non-Vegetarian')], max_length=100, null=True)),
                ('title', models.CharField(max_length=100, null=True)),
                ('ingredients', models.TextField(max_length=100, null=True)),
                ('instructions', models.TextField(max_length=100, null=True)),
                ('prep_time', models.PositiveIntegerField(max_length=100, null=True)),
                ('cooking_time', models.PositiveIntegerField(max_length=100, null=True)),
                ('total_time', models.PositiveIntegerField(max_length=100, null=True)),
                ('nutrition', models.TextField(max_length=100, null=True)),
                ('image', models.ImageField(null=True, upload_to='Media/Recipe_Image')),
                ('calories', models.PositiveIntegerField(max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipemodel', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
