# Generated by Django 5.1.1 on 2024-10-20 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0006_alter_creatorprofilemodel_user_recipemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipemodel',
            name='calories',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='recipemodel',
            name='cooking_time',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='recipemodel',
            name='prep_time',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='recipemodel',
            name='total_time',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
