# Generated by Django 5.1.1 on 2024-10-20 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0007_alter_recipemodel_calories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipemodel',
            name='ingredients',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='recipemodel',
            name='instructions',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='recipemodel',
            name='nutrition',
            field=models.TextField(null=True),
        ),
    ]
