# Generated by Django 5.1.1 on 2024-10-20 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0008_alter_recipemodel_ingredients_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatorprofilemodel',
            name='Achievements',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='creatorprofilemodel',
            name='Bio',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='creatorprofilemodel',
            name='Followers',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='creatorprofilemodel',
            name='Specialties',
            field=models.CharField(choices=[('desserts', 'Desserts'), ('vegan_recipes', 'VeganRecipes')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='viewersprofilemodel',
            name='Interests',
            field=models.CharField(choices=[('desserts', 'Desserts'), ('vegan_recipes', 'VeganRecipes')], max_length=100, null=True),
        ),
    ]
