# Generated by Django 5.1.1 on 2024-10-20 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0009_creatorprofilemodel_achievements_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creatorprofilemodel',
            name='Followers',
            field=models.PositiveIntegerField(max_length=100, null=True),
        ),
    ]
