# Generated by Django 5.1.1 on 2024-10-21 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0012_remove_creatorprofilemodel_achievements_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('recruiter', 'Recruiter'), ('seeker', 'Seeker')], max_length=100, null=True),
        ),
    ]
