# Generated by Django 5.1.1 on 2024-10-21 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0013_alter_customuser_user_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='creatorProfileModel',
            new_name='recruiterProfileModel',
        ),
        migrations.RenameModel(
            old_name='viewersProfileModel',
            new_name='seekerProfileModel',
        ),
    ]
