# Generated by Django 5.1.1 on 2024-10-21 05:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0014_rename_creatorprofilemodel_recruiterprofilemodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='Profile_Pic',
            field=models.ImageField(null=True, upload_to='Media/Profile_Pic'),
        ),
        migrations.AlterField(
            model_name='recruiterprofilemodel',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recruiterProfile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='seekerprofilemodel',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seekerProfile', to=settings.AUTH_USER_MODEL),
        ),
    ]
