# Generated by Django 5.1.1 on 2024-10-23 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0016_customuser_contact_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='contact_no',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
