# Generated by Django 5.0.6 on 2024-10-23 04:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0017_alter_customuser_contact_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('openings', models.PositiveIntegerField()),
                ('category', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('vancancy', models.CharField(max_length=100)),
                ('skills_required', models.CharField(max_length=100)),
                ('job_Pic', models.ImageField(null=True, upload_to='Media/Profile_Pic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
