# Generated by Django 5.0.6 on 2024-10-23 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0018_jobmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobmodel',
            name='openings',
            field=models.TextField(),
        ),
    ]
