# Generated by Django 5.0.7 on 2024-10-27 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0020_jobapplymodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobmodel',
            name='skills_required',
        ),
        migrations.AddField(
            model_name='jobmodel',
            name='skills',
            field=models.CharField(choices=[('Python', 'Python'), ('Java', 'Java'), ('C++', 'C++'), ('Data Science', 'Data Science'), ('Machine Learning', 'Machine Learning')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='seekerprofilemodel',
            name='skills',
            field=models.CharField(choices=[('Python', 'Python'), ('Java', 'Java'), ('C++', 'C++'), ('Data Science', 'Data Science'), ('Machine Learning', 'Machine Learning')], max_length=100, null=True),
        ),
    ]
